AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Master template refers to sub-templates
Metadata:

Parameters:
  DevAwsAccountId:
    Description: AWS account ID for development account
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
  ProdAwsAccountId:
    Description: AWS account ID for production account
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
  S3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/). It cannot start with forward slash (/) because that is automatically appended.
    Default: serverless-enterprise-cicd/
    Description: S3 key prefix for the release pipeline assets. Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/). It cannot start with forward slash (/) because that is automatically appended. It will typically end with a forward slash.
    Type: String

Conditions:
  UsingDefaultBucket: !Equals [!Ref S3BucketName, 'release-pipeline']

Resources:
  AccountStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DevAwsAccountId: !Ref DevAwsAccountId
        ProdAwsAccountId: !Ref ProdAwsAccountId
      TemplateURL: !Sub 
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${S3KeyPrefix}templates/account.template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref S3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${S3BucketName}-${AWS::Region}', !Ref S3BucketName]
      TimeoutInMinutes: 60